<Display>
    id: display
    orientation: "vertical"
    size: root.width, root.height

<DisplayLabel>
    halign: "left"
    valign: "center"
    text_size: self.size

<Header>
    cols: 4
    size_hint: 1,1
    DisplayLabel:
        text: "Name"
        bold: True

    DisplayLabel:
        text: "Price"
        bold: True

    DisplayLabel:
        text: ""
        bold: True

    DisplayLabel:
        text: ""
        bold: True