#:import Toolbar Toolbar
#:import Display displayMain

<Screen>
    id: sc
    size: self.width, self.height

    BoxLayout:
        id: bl
        orientation: "horizontal"
        size: root.width, root.height
        padding: 50,0,0,0
        Toolbar:
            id: toolbar
            size_hint: .3, 1
            pos_hint: {"top": 1}

        Display:
            id: display
            size_hint: .65, 1

